FROM grafana/k6

COPY scenario-INIT.js /config/scenario-INIT.js
COPY scenario-DATA_WRITE.js /config/scenario-DATA_WRITE.js
COPY scenario-DATA_LIST.js /config/scenario-DATA_LIST.js
COPY scenario-DATA_SIMPLE_ANALYTIC.js /config/scenario-DATA_SIMPLE_ANALYTIC.js

